[EntityEditorProps(category: "GameScripted/ScriptWizard", description: "ScriptWizard generated script file.")]
class PR_ScenarioFrameworkAreaClass : SCR_ScenarioFrameworkAreaClass
{
};

// Helper class for designer to specify what tasks will be available in this area
/*[BaseContainerProps()]
class SCR_ScenarioFrameworkTaskType
{
	[Attribute("Type of task", UIWidgets.ComboBox, enums: ParamEnumArray.FromEnum(SCR_ESFTaskType))]
	protected SCR_ESFTaskType m_eTypeOfTask;

	SCR_ESFTaskType GetTaskType()
	{
		return m_eTypeOfTask;
	}
}*/


/*
* Class is managing the area including the Slots (prefab Slot.et).
* The Slots should be placed in its hierarchy.
* GameModePatrolManager will select one instance of this type and will start to populate it based on the selected task
*
*/

enum PR_ETaskType
{
	CLEAR_AREA = 0,
	DEFEND, //Defend
	DELIVER, //Deliver
	DESTROY,
	EXTRACTION,
	KILL,
	MOVE,
	LOGIC_COUNTER//Logic Counter
};

enum PR_ETaskSide
{
	"US" = 0,			// 0  default
	"USSR" = 1,				// 1
	"FIA" = 2				// 2
};

enum PR_ETaskActivation
{
	SAME_AS_PARENT = 0,
	ON_TRIGGER_ACTIVATION,
	ON_AREA_TRIGGER_ACTIVATION,
	//ON_INIT,
	//ON_TASKS_INIT,
	CUSTOM1,
	CUSTOM2,
	CUSTOM3,
	CUSTOM4
};

enum PR_EActivationPresence
{
	PLAYER = 0,
	ANY_CHARACTER,
	SPECIFIC_CLASS,
	SPECIFIC_PREFAB_NAME
};

class PR_ScenarioFrameworkArea : SCR_ScenarioFrameworkArea
{
	//--- *** PR TASK: TASK CREATATION ***
	//--- Task type
	[Attribute("0", UIWidgets.ComboBox, "Task type. I.E. CLEAR_AREA, DEFEND, etc...  ", enums: ParamEnumArray.FromEnum(PR_ETaskType), category: "PR TASK: Task Creatation")]
	protected PR_ETaskType m_eTaskType;

	//--- Task activation
	static string sTaskActText1 = "How and when is the task is created and shown as avaliable.  \n\n";
	static string sTaskActText2 = "SAME_AS_PARENT - Task will be generated on mission start  \n";
	static string sTaskActText3 = "ON_TRIGGER_ACTIVATION - Task will be generated by a trigger being called from another task  \n";
	static string sTaskActText4 = "ON_AREA_TRIGGER_ACTIVATION - Task will be generated from this 'Trigger' section (yellow sphere)'  \n";
	static string sTaskActText5 = "CUSTOM1-4 - Task will be generated from a custom call (This is unknown use atm)'  \n";
	[Attribute("0", UIWidgets.ComboBox, sTaskActText1+ sTaskActText2+ sTaskActText3+ sTaskActText4+ sTaskActText5, enums: ParamEnumArray.FromEnum(PR_ETaskActivation), category: "PR TASK: Task Creatation")]
	protected PR_ETaskActivation m_eTaskActivation;

	//--- Object name to place task on
	[Attribute(desc: "REQUIRED:  Object name to place main task on.  \n\nMost common name will be this GenericEntity's name  \nI.E. PR_Task_Destroy, TaskClearArea, etc...  ", category: "PR TASK: Task Creatation")]
	protected string m_sTaskEntityName;

	//--- Task title
	[Attribute(desc: "Task title: Short name  ", category: "PR TASK: Task Creatation")]
	protected string m_sTaskTitle;

	//--- Task description
	[Attribute(desc: "Task Description: Explain what the task is  ", category: "PR TASK: Task Creatation")]
	protected string m_sTaskDescription;

	//--- Amount of delay before creating task // need added
	[Attribute(desc: "Amount of delay before creating task. In seconds.  ToDo: <disabled for now>.  Not Used!!!  ", category: "PR TASK: Task Creatation")]
	protected int delayTimer;

	//--- Move marker to objective trigger entity
	[Attribute("false", UIWidgets.CheckBox,"Move marker to objective trigger entity? Shows map marker on objective location.  ", category: "PR TASK: Task Creatation")]
	protected bool m_bMoveMarkerToObjectiveEntity;

	//--- Hides task map marker on the map --- todo
	[Attribute("false", UIWidgets.CheckBox,"Hides task map marker on the map.  ToDo: <disabled for now>.  Not Used!!!  ", category: "PR TASK: Task Creatation")]
	protected bool m_bHideMapMarker;

	//--- Write logs to file
	[Attribute("false", UIWidgets.CheckBox,"Write logs to file  ", category: "PR TASK: Task Creatation")]
	protected bool m_bDebugLogs;

	//--- *** PR TASK: TASK CREATATION: DELIVER ***
	//--- Task title
	[Attribute(desc: "Task title: Short name (item picked up)  ", category: "PR TASK: Task Creatation: Deliver")]
	protected string m_sTaskTitleUpdated1;

	//--- Task description
	[Attribute(desc: "Task Description: Explain what the task is (item picked up)  ", category: "PR TASK: Task Creatation: Deliver")]
	protected string m_sTaskDescriptionUpdated1;

	//--- Task title
	[Attribute(desc: "Task title: Short name (item dropped)  ", category: "PR TASK: Task Creatation: Deliver")]
	protected string m_sTaskTitleUpdated2;

	//--- Task description
	[Attribute(desc: "Task Description: Explain what the task is (item dropped)  ", category: "PR TASK: Task Creatation: Deliver")]
	protected string m_sTaskDescriptionUpdated2;

	
	[Attribute(category: "PR TASK: Defend Params")]
	protected ref array<ref SCR_ScenarioFrameworkTaskDefendFactionSettings> m_aFactionSettings;
	
	
	//--- *** PR TASK: OBJECTIVE TRIGGER ***
	
	//--- PR TASK: Objective: Name
	//--- Object name to move task to
	static string sTaskObjNameText1 = "Object name used for various functions. If no name is given it will use the default 'Task Entity Name'  \n\n";
	static string sTaskObjNameText2 = "Can be the entity name of vehicles, triggers, areas, etc...  \n";
	static string sTaskObjNameText3 = "In the case of Destroy or Kill tasks, this will be the entity to destroy.  \n";
	static string sTaskObjNameText4 = "Location for task completion trigger & detailed task location on map.  \n";
	static string sTaskObjNameText5 = "Location for 'Object To Spawn'.  \n";
	[Attribute(desc: sTaskObjNameText1+ sTaskObjNameText2+ sTaskObjNameText3+ sTaskObjNameText4+ sTaskObjNameText5, category: "PR TASK: Objective:  Name")]
	protected string m_sTaskObjectiveEntityName;

	//--- PR TASK: Objective: Asset
	//--- ASSET Group side to complete the task
	[Attribute("0", UIWidgets.ComboBox, "Faction to complete the task.  ", enums: ParamEnumArray.FromEnum(PR_ETaskSide), category: "PR TASK: Objective:  Asset")]
	//protected PR_ETaskSide ASSET_ActivatedByThisFaction;
	protected PR_ETaskSide m_eActivatedByThisFaction;// = ASSET_ActivatedByThisFaction;

	//--- ASSET Resource name of object to be spawned  // need work
	[Attribute("",desc: "Resource name of the object to be spawned.  ToDo: <disabled for now>.  Not Used!!!  ", category: "PR TASK: Objective:  Asset")] // PR_ScenarioFrameworkSlotBase
	//protected ResourceName ASSET_ObjectToSpawn;
	protected ResourceName m_sObjectToSpawn;// = ASSET_ObjectToSpawn;

	//--- ASSET Name of entity used for identification // need added
	[Attribute(desc: "Name of the entity used for identification.  ToDo: <disabled for now>.  Not Used!!!  ", category: "PR TASK: Objective:  Asset")]; // PR_ScenarioFrameworkSlotBase
	//protected string ASSET_ID;
	protected string m_sID;// = ASSET_ID;

	//--- ASSET Use existing world asset // need added
	[Attribute(desc: "This won't spawn new object, but it will rather use the object already existing in the world.  ToDo: <disabled for now>.  Not Used!!!  ", category: "PR TASK: Objective:  Asset")] // PR_ScenarioFrameworkSlotBase
	//protected bool ASSET_UseExistingWorldAsset;
 	protected bool m_bUseExistingWorldAsset;// = ASSET_UseExistingWorldAsset;

	//--- ASSET Override object displayname // need added
	[Attribute(desc: "Overrides display name of the spawned object for task purposes.  ToDo: <disabled for now>.  Not Used!!!  ", category: "PR TASK: Objective:  Asset")] // PR_ScenarioFrameworkSlotBase
	//protected string ASSET_OverrideObjectDisplayName;
	protected string m_sOverrideObjectDisplayName;// = ASSET_OverrideObjectDisplayName;


	//--- TRIGGER Completion radius
	[Attribute("10", UIWidgets.Slider,"Area completion radius for task. DEFAULT: 10  ", category: "PR TASK: Objective:  Trigger", params: "0 2000 0.5")]
	//float TRIGGER_AreaRadius;
	protected float m_fTaskRadius;// = TRIGGER_AreaRadius;

	//--- TRIGGER Activation presence - PLAYER, ANY_CHARACTER, SPECIFIC_CLASS, SPECIFIC_PREFAB_NAME
	[Attribute("0", UIWidgets.ComboBox, "By whom the trigger is activated", "", ParamEnumArray.FromEnum(PR_EActivationPresence), category: "PR TASK: Objective:  Trigger")]
	protected PR_EActivationPresence m_eActivationPresence;

	//--- TRIGGER Specific class names - <array> // need added
	[Attribute(desc: "If SPECIFIC_CLASS is selected, fill the class name here.", category: "PR TASK: Objective:  Trigger")]
	protected ref array<string> m_aSpecificClassNames; //m_aSpecificClassNames

	//--- TRIGGER Specific prefab names - <array> // need added
	[Attribute(desc: "If SPECIFIC_PREFAB_NAME is selected, fill the class name here.", category: "PR TASK: Objective:  Trigger")]
	protected ref array<ResourceName> m_aSpecificPrefabNames; //m_aSpecificPrefabNames

	//--- TRIGGER Activated by this faction - make pull down list // need added
	[Attribute(desc: "Faction which is used for area control calculation. Leave empty for any faction.", category: "PR TASK: Objective:  Trigger")]
	protected FactionKey m_sOwnerFactionKey; //m_sOwnerFactionKey

	//--- TRIGGER Custom trigger conditions - <array> // need added
	[Attribute(uiwidget: UIWidgets.Object, desc: "Here you can input custom trigger conditions that you can create by extending the SCR_CustomTriggerConditions", category: "PR TASK: Objective:  Trigger")]
	protected ref array<ref SCR_CustomTriggerConditions> m_aCustomTriggerConditions; //m_aCustomTriggerConditions

	//--- TRIGGER Once - checkbox
	[Attribute(defvalue: "1", UIWidgets.CheckBox, desc: "Activate the trigger once or everytime the activation condition is true?", category: "PR TASK: Objective:  Trigger")]
	protected bool m_Once; // multiple declaration of m_bOnce

	//--- TRIGGER Update rate - slider
	[Attribute(defvalue: "1", UIWidgets.Slider, desc: "How frequently is the trigger updated and performing calculations. Lower numbers will decrease performance.", params: "0 86400 1", category: "PR TASK: Objective:  Trigger")]
	protected float m_fUpdateRate;

	//--- TRIGGER Minimum players needed percentage - slider // MAKE THIS 0-100 PERCENT INSTEAD OF 0-1 SCALE   // need added
	[Attribute(defvalue: "0", UIWidgets.Slider, desc: "Minimum players needed to activate this trigger when PLAYER Activation presence is selected", params: "0 1 0.01", precision: 2, category: "PR TASK: Objective:  Trigger")]
	protected float	m_fMinimumPlayersNeededPercentage; //m_fMinimumPlayersNeededPercentage

	//--- TRIGGER Activation countdown timer - slider // need testing
	[Attribute(defvalue: "0", UIWidgets.Slider, desc: "For how long the trigger conditions must be true in order for the trigger to activate. If conditions become false, timer resets", params: "0 86400 1", category: "PR TASK: Objective:  Trigger")]
	protected float m_fActivationCountdownTimer; //m_fActivationCountdownTimer

	//--- TRIGGER Notification enabled - checkbox // need testing
/*	// Probably just comment these out for now until i can figure out how to use*/
	[Attribute(defvalue: "0", UIWidgets.CheckBox, desc: "Whether or not the notification is allowed to be displayed", category: "PR TASK: Objective:  Trigger")]
	protected bool m_bNotificationEnabled; //m_bNotificationEnabled
	
	//--- TRIGGER Player activation notification title - text // need testing
	[Attribute(desc: "Notification title text that will be displayed when the PLAYER Activation presence is selected", category: "PR TASK: Objective:  Trigger")]
	protected string m_sPlayerActivationNotificationTitle; //m_sPlayerActivationNotificationTitle

	//--- TRIGGER Enable audio - checkbox // need testing
/*	// Probably just comment these out for now until i can figure out how to use*/
	[Attribute(defvalue: "0", UIWidgets.CheckBox, desc: "Whether or not the audio sound is played and affected by the trigger", category: "PR TASK: Objective:  Trigger")]
	protected bool m_bEnableAudio;

	//--- TRIGGER Countdown audio - text // need testing
/*	// Probably just comment these out for now until i can figure out how to use*/
	[Attribute("", UIWidgets.EditBox, desc: "Audio sound that will be playing when countdown is active.", category: "PR TASK: Objective:  Trigger")]
	protected string m_sCountdownAudio;

	//--- TASK STATUS
	
	//[Attribute("", desc: "Name of the task in list of tasks", category: "PR TASK: Objective:  Task")]		 // need work
	//protected string m_sMatchingTaskTitle;
	
	//[Attribute("", desc: "Description of the task", category: "PR TASK: Objective:  Task")]	 // need work	//TODO: make config, memory
	//protected string m_sMatchingTaskDescription;
	
	[Attribute("", desc: "If spawning tasks using the actions below.\n\nAdd  _1  to end of the task name", category: "PR TASK: Objective:  Read Hint Below!")] //---
	protected string UnusedReadHoverHint;
	
	//--- OnTaskFinish - "What to do once task is finished"
	[Attribute(defvalue: "1", desc: "What to do once task is finished", UIWidgets.Auto, category: "PR TASK: Objective:  On Task Finish")];
	protected ref array<ref SCR_ScenarioFrameworkActionBase> m_aActionsOnFinished;

	//--- OnTaskCreate
	[Attribute(defvalue: "1", desc: "What to do once task is created", UIWidgets.Auto, category: "PR TASK: Objective:  On Task Create")];
	protected ref array<ref SCR_ScenarioFrameworkActionBase> m_aActionsOnCreated;

	//--- OnTaskFailed
	[Attribute(defvalue: "1", desc: "What to do once task is failed", UIWidgets.Auto, category: "PR TASK: Objective:  On Task Failed")];
	protected ref array<ref SCR_ScenarioFrameworkActionBase> m_aActionsOnFailed;

	//--- OnTaskProgress
	[Attribute(defvalue: "1", desc: "What to do once task progressed", UIWidgets.Auto, category: "PR TASK: Objective:  On Task Progress")];
	protected ref array<ref SCR_ScenarioFrameworkActionBase> m_aActionsOnProgress;

	//--- OnTaskUpdated
	[Attribute(defvalue: "1", desc: "What to do once task is updated", UIWidgets.Auto, category: "PR TASK: Objective:  On Task Updated")];
	protected ref array<ref SCR_ScenarioFrameworkActionBase> m_aActionsOnUpdated;
		


	//--- Reference tasker script
	private ref PR_TaskSpawner m_PR_TaskSpawner;

	PR_TaskSpawner PR_Tasker()
	{
		return m_PR_TaskSpawner;
	}

	//--- Create task from Init
	/*override*/ void Init(SCR_ScenarioFrameworkArea area = null, SCR_ScenarioFrameworkEActivationType activation = SCR_ScenarioFrameworkEActivationType.SAME_AS_PARENT, bool bInit = true)
	{
		//--- Start PR_Tasker
		IEntity m_iArea = GetOwner();
	//	SCR_ScenarioFrameworkTaskDefendDefendingFaction defender = SCR_ScenarioFrameworkTaskDefendDefendingFaction.Cast(m_aFactionSettings[0]);
	//	SCR_ScenarioFrameworkTaskDefendAttackingFaction attacker = SCR_ScenarioFrameworkTaskDefendAttackingFaction.Cast(m_aFactionSettings[1]);
		PrintFormat("[PR_ScenarioFramework]: Init: PR_Area: %1",m_iArea);

		array<string> m_sTaskStringArray = {
			m_sTaskEntityName,
			m_sTaskTitle,
			m_sTaskDescription,
			m_sTaskObjectiveEntityName,
			m_sPlayerActivationNotificationTitle,
			m_sCountdownAudio,
			m_sTaskTitleUpdated1,
			m_sTaskDescriptionUpdated1,
			m_sTaskTitleUpdated2,
			m_sTaskDescriptionUpdated2
			/*,m_sMatchingTaskTitle,m_sMatchingTaskDescription*/
		};
		array<int> m_iTaskIntArray = {m_eTaskType,m_eTaskActivation,m_eActivatedByThisFaction,m_eActivationPresence};
		array<bool> m_bTaskBoolArray = {m_bMoveMarkerToObjectiveEntity,m_bHideMapMarker,m_bDebugLogs,m_Once,m_bNotificationEnabled,m_bEnableAudio};
		array<float> m_fTaskFloatArray = {m_fTaskRadius,m_fUpdateRate,m_fActivationCountdownTimer};
		array<ResourceName> m_rTaskResourceNameArray = {m_sObjectToSpawn};
		array<array<ref SCR_ScenarioFrameworkActionBase>> m_aActionsArray = {m_aActionsOnFinished,m_aActionsOnCreated,m_aActionsOnFailed,m_aActionsOnProgress,m_aActionsOnUpdated};
		//PrintFormat("[PR_ScenarioFramework]: m_aActionsArray: %1",m_aActionsArray);
		//int delay = 2000;
		
		m_PR_TaskSpawner = new PR_TaskSpawner();

		m_PR_TaskSpawner.PR_Tasker(
			m_iArea,
			m_sTaskStringArray,
			m_iTaskIntArray,
			m_bTaskBoolArray,
			m_fTaskFloatArray,
			m_rTaskResourceNameArray,
			m_aActionsArray,
			m_aFactionSettings
		);
		//--- End PR_Tasker

		if (m_bInitiated)
			return;

		if (m_eActivationType != SCR_ScenarioFrameworkEActivationType.ON_INIT)
			PrintFormat("ScenarioFramework: Area %1 is set to %2 activation type, but area will always spawn on Init as default", GetOwner().GetName(), activation, LogLevel.WARNING);

		SpawnTrigger();
		// Area is always spawned on the start
		super.Init(this, SCR_ScenarioFrameworkEActivationType.ON_INIT);
		
		if (m_Trigger)
		{
			foreach(SCR_ScenarioFrameworkActionBase triggerAction : m_aTriggerActions)
			{
				triggerAction.Init(m_Trigger);
			}
		}
		
		m_OnAreaInit.Invoke();
		
		/*if (!m_bUseExistingWorldAsset) // trying spawn object
		{
			m_Entity = SCR_ScenarioFrameworkSlotBase.SpawnAsset();
		}
		else
		{
			SCR_ScenarioFrameworkSlotBase.QueryObjectsInRange();	//sets the m_Entity in subsequent callback
		}*/
	}
	
	
//	[Attribute(uiwidget: UIWidgets.ResourcePickerThumbnail, "Trigger for area", category: "Trigger")]
//	protected ResourceName 					m_sTriggerResource;

//	[Attribute(defvalue: "5.0", UIWidgets.Slider, params: "1.0 1000.0 0.5", desc: "Radius of the trigger area", category: "Trigger")]
//	protected float							m_fAreaRadius;
	
//	[Attribute(defvalue: "1", UIWidgets.CheckBox, desc: "Activate the trigger once or everytime the activation condition is true?", category: "Trigger")]
//	protected bool		m_bOnce;

//	protected SCR_BaseTriggerEntity											m_Trigger;
//	protected ref ScriptInvoker<SCR_ScenarioFrameworkArea, SCR_ScenarioFrameworkEActivationType>				m_OnTriggerActivated;
//	protected ref ScriptInvoker												m_OnAreaInit = new ScriptInvoker();
//	protected SCR_GameModeSFManager 										m_GameModeManager;
//	protected bool															m_bAreaSelected = false;
//	protected SCR_BaseTask 													m_Task;
//	protected string	 													m_sItemDeliveryPointName;
//	protected SCR_ScenarioFrameworkLayerTask								m_LayerTask;
//	protected SCR_ScenarioFrameworkSlotTask									m_TaskSubject; 				//storing this one in order to get the task title and description
	
//	[Attribute(UIWidgets.Auto, category: "OnActivation")];
//	protected ref array<ref SCR_ScenarioFrameworkActionBase>	m_aTriggerActions;

/*#ifdef WORKBENCH
	[Attribute(defvalue: "0", desc: "Show the debug shapes in Workbench", category: "Debug")];
	protected bool							m_bShowDebugShapesInWorkbench;
#endif	*/

	//------------------------------------------------------------------------------------------------
/*	SCR_BaseTask GetTask()
	{
		return m_Task;
	}*/
	
	//------------------------------------------------------------------------------------------------
/*	SCR_ScenarioFrameworkSlotTask GetTaskSubject()
	{
		return m_TaskSubject;
	}*/

	//------------------------------------------------------------------------------------------------
/*	void SetTaskSubject(SCR_ScenarioFrameworkSlotTask taskSubject)
	{
		m_TaskSubject = taskSubject;
	}*/
	//------------------------------------------------------------------------------------------------
/*	SCR_ScenarioFrameworkLayerTask GetLayerTask()
	{
		return m_LayerTask;
	}*/
	
	//------------------------------------------------------------------------------------------------
/*	void SetLayerTask(SCR_ScenarioFrameworkLayerTask layerTask)
	{
		m_LayerTask = layerTask;
	}*/
	
	//------------------------------------------------------------------------------------------------
/*	string GetLayerTaskName()
	{
		return m_LayerTask.GetOwner().GetName();
	}*/
	
	//------------------------------------------------------------------------------------------------
/*	SCR_ESFTaskType GetLayerTaskType()
	{
		return m_LayerTask.GetTaskType();
	}*/

	//------------------------------------------------------------------------------------------------
/*	string GetDeliveryPointName()
	{
		return m_sItemDeliveryPointName;
	}*/

	//------------------------------------------------------------------------------------------------
/*	void StoreDeliveryPoint(string sDeliveryPointName)
	{
		m_sItemDeliveryPointName = sDeliveryPointName;
		if (!SCR_TaskDeliver.Cast(m_Task))
			return;

		SCR_TaskDeliver.Cast(m_Task).SetTriggerNameToDeliver(sDeliveryPointName);
	}*/

	//------------------------------------------------------------------------------------------------
/*	void StoreTaskToArea(SCR_BaseTask task)
	{
		m_Task = task;
	}*/
	
	//------------------------------------------------------------------------------------------------
/*	void StoreState(out SCR_ScenarioFrameworkAreaStruct areaStruct)
	{
		//Checks if area is named. If it is not, we cannot use it for serialization
		if (GetName().IsEmpty())
		{
			delete areaStruct;
			return;
		}
		
		areaStruct.IncreaseStructVarCount();
		areaStruct.SetName(GetName());
		
		StoreSelectedArea(areaStruct);
		StoreDeliveryPoint(areaStruct);
		
		StoreTerminationStatus(areaStruct);
		StoreRepeatedSpawn(areaStruct);
		StoreLayerTask(areaStruct);
		
		bool handledLayers;
		StoreChildren(areaStruct, handledLayers);
		bool handledLogics;
		StoreLogic(areaStruct, handledLogics);
		
		CleanEmptyStoredLayers(areaStruct, handledLayers);
		CleanEmptyStoredLogic(areaStruct, handledLogics);
		CleanAreaStructs(areaStruct);
	}*/

	//------------------------------------------------------------------------------------------------
	//! Handles area selection
/*	protected void StoreSelectedArea(SCR_ScenarioFrameworkAreaStruct areaStruct)
	{
		if (m_bAreaSelected)
		{
			areaStruct.IncreaseStructVarCount();
			areaStruct.SetAreaSelected(1);
		}
		else
		{
			areaStruct.UnregV("m_bAreaSelected");
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! Delivery point handling
/*	protected void StoreDeliveryPoint(SCR_ScenarioFrameworkAreaStruct areaStruct)
	{
		if (!m_sItemDeliveryPointName.IsEmpty())
		{
			areaStruct.IncreaseStructVarCount();
			areaStruct.SetDeliveryPointNameForItem(GetDeliveryPointName());
		}
		else 
		{
			areaStruct.UnregV("m_sItemDeliveryPointName");
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! Marks if this was terminated - either by death or deletion
/*	protected void StoreTerminationStatus(SCR_ScenarioFrameworkAreaStruct areaStruct)
	{
		if (GetIsTerminated())
		{
			areaStruct.IncreaseStructVarCount();
			areaStruct.SetIsTerminated(true);
		}
		else
		{
			areaStruct.UnregV("m_bIsTerminated");
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! Repeated spawn handling
/*	protected void StoreRepeatedSpawn(SCR_ScenarioFrameworkAreaStruct areaStruct)
	{
		if (GetEnableRepeatedSpawn())
		{
			areaStruct.IncreaseStructVarCount();
			areaStruct.SetEnableRepeatedSpawn(GetEnableRepeatedSpawn());
			if (GetRepeatedSpawnNumber() != -1)
			{
				areaStruct.IncreaseStructVarCount();
				areaStruct.SetRepeatedSpawnNumber(GetRepeatedSpawnNumber());
			}
			else
			{
				areaStruct.UnregV("m_iRepeatedSpawnNumber");
			}
		}
		else
		{
			areaStruct.UnregV("m_bEnableRepeatedSpawn");
			areaStruct.UnregV("m_iRepeatedSpawnNumber");
		}	
	}*/

	//------------------------------------------------------------------------------------------------
	//! Layer Task handling
/*	protected void StoreLayerTask(SCR_ScenarioFrameworkAreaStruct areaStruct)
	{
		if (m_LayerTask)
		{
			areaStruct.SetLayerTaskName(GetLayerTaskName());
			areaStruct.IncreaseStructVarCount();
		}
		else	
		{
			areaStruct.UnregV("m_sLayerTaskName");
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! Children handling
/*	protected void StoreChildren(SCR_ScenarioFrameworkAreaStruct areaStruct, bool handledLayers)
	{
		if (m_aChildren.IsEmpty())
		{
			areaStruct.UnregV("m_aLayersStructs");
		}
		else
		{
			if (GetSpawnChildrenType() != SCR_EScenarioFrameworkSpawnChildrenType.ALL)
			{
				array<SCR_ScenarioFrameworkLayerBase> m_aRandomlySpawnedChildrenLayerBases = GetRandomlySpawnedChildren();
				foreach (SCR_ScenarioFrameworkLayerBase child : m_aRandomlySpawnedChildrenLayerBases)
				{
					areaStruct.InsertRandomlySpawnedChildren(child.GetName());
				}
				areaStruct.IncreaseStructVarCount();
			}
			else
				areaStruct.UnregV("m_aRandomlySpawnedChildren");
			
			areaStruct.IncreaseStructVarCount();
			handledLayers = true;
			foreach (SCR_ScenarioFrameworkLayerBase layer : m_aChildren)
			{
				areaStruct.StoreLayerState(layer);
			}
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! Logics handling
/*	protected void StoreLogic(SCR_ScenarioFrameworkAreaStruct areaStruct, bool handledLogics)
	{
		if (m_aLogic.IsEmpty())
		{
			areaStruct.UnregV("m_aLogicStructs");
		}
		else
		{
			areaStruct.IncreaseStructVarCount();
			handledLogics = true;
			foreach (SCR_ScenarioFrameworkLogic logic : m_aLogic)
			{
				areaStruct.StoreLogicState(logic);
			}
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! //Cleaning empty layers
/*	protected void CleanEmptyStoredLayers(SCR_ScenarioFrameworkAreaStruct areaStruct, bool handledLayers)
	{
		if (areaStruct.GetLayerStructs())
		{
			if (areaStruct.GetLayerStructs().IsEmpty())
			{
				areaStruct.UnregV("m_aLayersStructs");
				if (handledLayers)
					areaStruct.DecreaseStructVarCount();
			}
		}
		else
		{
			if (handledLayers)
				areaStruct.DecreaseStructVarCount();
			
			areaStruct.UnregV("m_aLayersStructs");
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! //Cleaning empty layers
/*	protected void CleanEmptyStoredLogic(SCR_ScenarioFrameworkAreaStruct areaStruct, bool handledLogics)
	{
		if (areaStruct.GetLogicStructs())
		{
			if (areaStruct.GetLogicStructs().IsEmpty())
			{
				areaStruct.UnregV("m_aLogicStructs");
				if (handledLogics)
					areaStruct.DecreaseStructVarCount();
			}
		}
		else
		{
			if (handledLogics)
				areaStruct.DecreaseStructVarCount();
			
			areaStruct.UnregV("m_aLogicStructs");
		}
	}*/

	//------------------------------------------------------------------------------------------------
	//! //Cleaning empty structs that are unnecessary to be saved and removing other variables that are there due to inheritance
/*	protected void CleanAreaStructs(SCR_ScenarioFrameworkAreaStruct areaStruct)
	{
		areaStruct.ClearEmptyLayerStructs(areaStruct.GetLayerStructs());
		areaStruct.ClearEmptyLogicStructs(areaStruct.GetLogicStructs());

		areaStruct.UnregV("m_aAIPrefabsForRemoval");
		areaStruct.UnregV("m_sRandomlySpawnedObject");
		areaStruct.UnregV("m_iLayerTaskState");
	}*/

	//------------------------------------------------------------------------------------------------
/*	SCR_ScenarioFrameworkLayerTask Create()
	{
		array<SCR_ScenarioFrameworkLayerBase> aSlotsOut = {};
		GetAllSlots(aSlotsOut);
		if (aSlotsOut.IsEmpty())
			return null;

		SCR_ScenarioFrameworkLayerBase layer = SCR_ScenarioFrameworkLayerBase.Cast(aSlotsOut.GetRandomElement());
		if (layer)
			layer.Init(this);

		return SCR_ScenarioFrameworkLayerTask.Cast(layer);
	}*/

	//------------------------------------------------------------------------------------------------
/*	SCR_ScenarioFrameworkLayerTask Create(SCR_ESFTaskType eTaskType)
	{
		array<SCR_ScenarioFrameworkLayerBase> aSlotsOut = {};
		GetSuitableLayersForTaskType(aSlotsOut, eTaskType);
		if (aSlotsOut.IsEmpty())
			return null;

		//there might be more layers in the area conforming to the task type (i.e. 2x the Truck task)
		m_LayerTask = SCR_ScenarioFrameworkLayerTask.Cast(aSlotsOut.GetRandomElement());
		if (m_LayerTask)
			m_LayerTask.Init(this, SCR_ScenarioFrameworkEActivationType.ON_TASKS_INIT);

		return m_LayerTask;
	}*/

	//------------------------------------------------------------------------------------------------
/*	void Create(SCR_ScenarioFrameworkLayerTask layerTask)
	{
		if (!layerTask)
			return;
		
		m_LayerTask = layerTask;
		m_LayerTask.Init(this, SCR_ScenarioFrameworkEActivationType.ON_TASKS_INIT);
	}*/
	
	//------------------------------------------------------------------------------------------------
/*	SCR_BaseTriggerEntity GetTrigger()
	{
		return m_Trigger;
	}*/

	//------------------------------------------------------------------------------------------------
/*	void SpawnTrigger()
	{
		Resource resource = Resource.Load(m_sTriggerResource);
		if (!resource)
			return;

		EntitySpawnParams spawnParams = new EntitySpawnParams();
		spawnParams.TransformMode = ETransformMode.WORLD;
		GetOwner().GetWorldTransform(spawnParams.Transform);

		//--- Apply rotation
		vector angles = Math3D.MatrixToAngles(spawnParams.Transform);
		Math3D.AnglesToMatrix(angles, spawnParams.Transform);


		//--- Spawn the prefab
		BaseResourceObject resourceObject = resource.GetResource();
		if (!resourceObject)
			return;

		string resourceName = resourceObject.GetResourceName();
		m_Trigger = SCR_BaseTriggerEntity.Cast(GetGame().SpawnEntityPrefab(resource, GetGame().GetWorld(), spawnParams));
		if (!m_Trigger)
			return;

		//m_Trigger.Show(false);
		m_Trigger.SetSphereRadius(m_fAreaRadius);
		m_Trigger.GetOnActivate().Insert(OnAreaTriggerActivated);
		
		SCR_CharacterTriggerEntity characterTrigger = SCR_CharacterTriggerEntity.Cast(m_Trigger);
		if (characterTrigger)
			characterTrigger.SetOnce(m_bOnce);
	}*/

	//------------------------------------------------------------------------------------------------
/*	void MoveTaskIconToArea(notnull SCR_BaseTask task)
	{
		task.SetOrigin(GetOwner().GetOrigin());

	}*/

	//------------------------------------------------------------------------------------------------
/*	bool GetIsTaskSuitableForArea(SCR_ESFTaskType eTaskType)
	{
		array<SCR_ESFTaskType> aTaskTypes = {};
		GetAvailableTaskTypes(aTaskTypes);
		if (aTaskTypes.IsEmpty())
			return false;

		return aTaskTypes.Find(eTaskType) != -1;
	}*/

	//------------------------------------------------------------------------------------------------
/*	void GetAvailableTaskTypes(out array<SCR_ESFTaskType> aTaskTypes)
	{
		array<SCR_ScenarioFrameworkLayerBase> aSlots = {};
		GetAllSlots(aSlots);
		SCR_ESFTaskType eType;
		SCR_ScenarioFrameworkLayerTask pos;
		foreach (SCR_ScenarioFrameworkLayerBase layer : aSlots)
		{
			pos = SCR_ScenarioFrameworkLayerTask.Cast(layer);
			if (!pos)
				continue;

			eType = pos.GetTaskType();
			if (aTaskTypes.Find(eType) == -1)
				aTaskTypes.Insert(eType);
		}
	}*/

	//------------------------------------------------------------------------------------------------
/*	void GetSuitableLayersForTaskType(out notnull array<SCR_ScenarioFrameworkLayerBase> aSlotsOut, SCR_ESFTaskType eTaskType)
	{
		SCR_ESFTaskType eType;
		array<SCR_ScenarioFrameworkLayerBase> aSlots = {};
		GetAllSlots(aSlots);
		SCR_ScenarioFrameworkLayerTask pos;
		foreach (SCR_ScenarioFrameworkLayerBase layer : aSlots)
		{
			pos = SCR_ScenarioFrameworkLayerTask.Cast(layer);
			if (!pos)
				continue;

			eType = pos.GetTaskType();
			if (eTaskType == eType)
				aSlotsOut.Insert(pos);
		}
	}*/

	//------------------------------------------------------------------------------------------------
/*	protected void GetAllSlots(out array<SCR_ScenarioFrameworkLayerBase> aSlots)
	{
		SCR_ScenarioFrameworkLayerBase slotComponent;
		IEntity child = GetOwner().GetChildren();
		while (child)
		{
			slotComponent = SCR_ScenarioFrameworkLayerBase.Cast(child.FindComponent(SCR_ScenarioFrameworkLayerBase));
			if (slotComponent)
			{
				aSlots.Insert(slotComponent);
			}
			child = child.GetSibling();
		}
	}*/

	//------------------------------------------------------------------------------------------------
/*	void SetAreaSelected(bool bSet)
	{
		 m_bAreaSelected = bSet;
	}*/

	//------------------------------------------------------------------------------------------------
/*	bool GetIsAreaSelected()
	{
		return m_bAreaSelected;
	}*/

	//------------------------------------------------------------------------------------------------
/*	void OnAreaTriggerActivated(IEntity entity)
	{
		if (m_OnTriggerActivated)
		{
			m_OnTriggerActivated.Invoke(this, SCR_ScenarioFrameworkEActivationType.ON_AREA_TRIGGER_ACTIVATION, false);
			m_OnTriggerActivated.Clear();
			if (!m_bOnce)
				return;
			
			m_Trigger.Deactivate();
		}
	}*/

	//------------------------------------------------------------------------------------------------
/*	ScriptInvoker GetOnAreaTriggerActivated()
	{
		if (!m_OnTriggerActivated)
			m_OnTriggerActivated = new ScriptInvoker<SCR_ScenarioFrameworkArea, SCR_ScenarioFrameworkEActivationType>();

		return m_OnTriggerActivated;
	}*/

	//------------------------------------------------------------------------------------------------
/*	ScriptInvoker GetOnAreaInit()
	{	
		return m_OnAreaInit;
	}*/



	//------------------------------------------------------------------------------------------------
	override void EOnFrame(IEntity owner, float timeSlice)
	{
		//Print("[PR_ScenarioFramework]: EOnFrame");
		if (m_Trigger)
			super.EOnFrame(owner, timeSlice);
	}

	//------------------------------------------------------------------------------------------------
	override void EOnInit(IEntity owner)
	{
		// pr start
	//	Print("[PR_ScenarioFramework]: EOnInit");
		
		SCR_BaseGameMode gameMode = SCR_BaseGameMode.Cast(GetGame().GetGameMode());
		if (!gameMode)
			return;

		SCR_GameModeSFManager m_GameModeManager = SCR_GameModeSFManager.Cast(gameMode.FindComponent(SCR_GameModeSFManager));
		if (m_GameModeManager)
			m_GameModeManager.RegisterArea(this);
	}


	
	override void OnPostInit(IEntity owner)
	{
	//	Print("[PR_ScenarioFramework]: OnPostInit");

		super.OnPostInit(owner);
		SetEventMask(owner, EntityEvent.INIT | EntityEvent.FRAME);
		
	/*	m_PRtasker.PR_Tasker(
			taskEntityName, // 0
			tType, // 1 taskType
			taskTitleDescription, // 2
			taskRadius, // 3
			actFaction, // 4 activatedByThisFaction
			taskObjectiveEntity, // 5
			moveMarkerToObjectiveEntity, // 6
			hideMapMarker, // 7
			debugLogs // 8
		);*/
	}
	
/*#ifdef WORKBENCH
	//------------------------------------------------------------------------------------------------
	override void _WB_AfterWorldUpdate(IEntity owner, float timeSlice)
	{
		DrawDebugShape(m_bShowDebugShapesInWorkbench);
	}
	
	//------------------------------------------------------------------------------------------------
	override bool _WB_OnKeyChanged(IEntity owner, BaseContainer src, string key, BaseContainerList ownerContainers, IEntity parent)
	{
		if (key == "m_bShowDebugShapesInWorkbench")
			DrawDebugShape(m_bShowDebugShapesInWorkbench);
		
		return false;
	}

	//------------------------------------------------------------------------------------------------
	void SCR_ScenarioFrameworkArea(IEntityComponentSource src, IEntity ent, IEntity parent)
	{
		m_iDebugShapeColor = ARGB(32, 0x99, 0xF3, 0x12);
		m_fDebugShapeRadius = m_fAreaRadius;
	}
#endif	*/
}
